services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: counter-backend
    stdin_open: true
    tty: true
    
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: counter-frontend
    

  proxy:
    image: nginx
    container_name: counter-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./counter.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/certificate.crt:/etc/nginx/certificate.crt
      - ./ssl/privateKey.key:/etc/nginx/private.key
